name: "Simple deployment workflow"
on: 
    push: 
        branches: 
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: "checksout the repository"
              uses: actions/checkout@v4


            - name: "Log in to Docker"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: "Resolve the image tag"
              id: tag_generator
              run: |
                echo "deployment_tag=$( git describe --always)" >> $GITHUB_OUTPUT
                echo "image_name=frontend" >> $GITHUB_OUTPUT
                
            
            - name: 'Delete any running container'
              run: |
                sudo docker stop frontend && sudo docker rm frontend
                
            - name: "Remove any images on the system"
              run: |
                sudo docker rmi -f $( sudo docker images -q)
                
            - name: "Build a Docker Image"
              run: |
                sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }} .
              
            
            
            - name: "Push the image to Docker Hub"
              run: |
                sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }} 
                


            - name: Deploy to frontend-ec2
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.AWS_EC2_INSTANCE_2 }}
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                    docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }}
                    docker stop ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }} || true
                    docker rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }} || true
                    docker run -d --name frontendbir -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }}